src/Presentation.Web/Models/BasketRemoveItemConfirmViewModel.cs
using System;
using System.ComponentModel;

namespace Easy.Commerce.Presentation.Web.Models
{
    [Serializable]
    public class BasketRemoveItemConfirmViewModel
    {
        [DisplayName("Id")]
        public virtual Guid Id { get; set; }

        [DisplayName("Sku")]
        public virtual string Sku { get; set; }
    }
}

src/Presentation.Web/Models/BasketRemoveItemViewModel.cs
using System;
using System.ComponentModel;

namespace Easy.Commerce.Presentation.Web.Models
{
    [Serializable]
    public class BasketRemoveItemViewModel
    {
        [DisplayName("Id")]
        public virtual Guid Id { get; set; }

        [DisplayName("Quantidade de Itens")]
        public virtual int ItemsQuantity { get; set; }

        [DisplayName("Moeda")]
        public virtual CurrencyIso Currency { get; set; }

        [DisplayName("Total")]
        public virtual decimal Total { get; set; }

        [DisplayName("Sku")]
        public virtual string Sku { get; set; }
    }
}

src/Presentation.Web/Models/CurrencyIso.cs
namespace Easy.Commerce.Presentation.Web.Models
{
    public enum CurrencyIso
    {
        BRL,

        USD
    }
}

src/Presentation.Web/Models/ErrorViewModel.cs
using System;

namespace Easy.Commerce.Presentation.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Presentation.Web/Controllers/BasketController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Easy.Commerce.Presentation.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RestSharp;

namespace Easy.Commerce.Presentation.Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RestClient client;

        public BasketController(IConfiguration configuration)
        {
            this.configuration = configuration;
            client = new RestClient(configuration["ApiEndpoint"]);
        }

        // GET: Basket
        public ActionResult Index()
        {
            return View();
        }

        // GET: Basket/Create
        public async Task<ActionResult> Create()
        {
            var request = new RestRequest("/v1/baskets", Method.POST);

            request.AddHeader("Content-Type", "application/json");
            request.RequestFormat = DataFormat.Json;
            var response = await client.ExecuteTaskAsync<object>(request);
            var content = JsonConvert.DeserializeObject<dynamic>(response?.Content);

            return View(new BasketCreatedViewModel { Id = content.id });
        }

        // POST: Basket/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddItem(BasketCreatedViewModel model)
        {
            try
            {
                var request = new RestRequest($"/v1/baskets/{model.Id}", Method.POST);

                request.AddHeader("Content-Type", "application/json");
                request.RequestFormat = DataFormat.Json;

                request.AddBody(new
                    {
                        sku = model.Sku,
	                    name = model.Name,
	                    quantity = model.Quantity,
	                    images = new List<string> { model.Image },
	                    currency = model.Currency,
	                    unityValue = model.UnityValue,
	                    total = model.Total,
                    });

                var response = await client.ExecuteTaskAsync<object>(request);
                var content = JsonConvert.DeserializeObject<dynamic>(response?.Content);

                var result = new BasketRemoveItemViewModel
                {
                    Id = content.id,
                    Currency = content.currency ?? CurrencyIso.BRL,
                    ItemsQuantity = content.items.Count,
                    Sku = model.Sku,
                    Total = content.total
                };

                return RedirectToAction(nameof(RemoveItem), result);
            }
            catch
            {
                return View();
            }
        }

        // GET: Basket
        public ActionResult RemoveItem(BasketRemoveItemViewModel model)
        {
            return View(model);
        }


        // POST: Basket/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveItem(BasketRemoveItemConfirmViewModel model)
        {
            try
            {
                var request = new RestRequest($"/v1/baskets/{model.Id}/items/{model.Sku}", Method.DELETE);

                request.AddHeader("Content-Type", "application/json");
                request.RequestFormat = DataFormat.Json;

                var response = await client.ExecuteTaskAsync<object>(request);

                return RedirectToAction(nameof(Congratulations));
            }
            catch
            {
                return View();
            }
        }

        // GET: Basket/Congratulations
        public ActionResult Congratulations()
        {
            return View();
        }
    }
}

src/Presentation.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Easy.Commerce.Presentation.Web.Models;

namespace Easy.Commerce.Presentation.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sandbox()
        {
            ViewData["Message"] = "Hora da diversão!";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Qualquer dúvida entre em contato.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Presentation.Web/Views/Basket/Congratulations.cshtml
@{
    ViewData["Title"] = "BasketDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Parabéns!</h2>

<div>
    <p>Você concluiu com sucesso o tutorial do Basket Microservices</p>
    <input type="button" value="Clique aqui para fazer o processo novamente" onclick="location.href='@Url.Action("Sandbox", "Home")'" />
</div>

src/Presentation.Web/Views/Basket/Create.cshtml
@model Easy.Commerce.Presentation.Web.Models.BasketCreatedViewModel

@{
    ViewData["Title"] = "BasketDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carrinho criado com sucesso!</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
</div>
<div>
    <p><strong>Passo 2</strong> - Adicionar um item no carrinho</p>
    <p>Preencha os campos abaixo:</p>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" />
                <label asp-for="Sku" class="control-label"></label>
                <input asp-for="Sku" class="form-control" />
                <span asp-validation-for="Sku" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnityValue" class="control-label"></label>
                <input asp-for="UnityValue" class="form-control" />
                <span asp-validation-for="UnityValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

src/Presentation.Web/Views/Basket/RemoveItem.cshtml
@model Easy.Commerce.Presentation.Web.Models.BasketRemoveItemViewModel

@{
    ViewData["Title"] = "BasketDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Item adicionado com sucesso!</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemsQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemsQuantity)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
</div>
<div>
    <p><strong>Passo 3</strong> - Remover um item no carrinho</p>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="RemoveItem">
                <input asp-for="Id" type="hidden" />
                <input asp-for="Sku" type="hidden" />
                <div class="form-group">
                    <input type="submit" value="Clique aqui para remover" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
</div>

src/Presentation.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contatos";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Gustavo Soares<br />
    Arquiteto de Software<br />
    <abbr title="Telefone">P:</abbr>
    (11) 97964-2125
</address>

<address>
    <strong>Suporte:</strong> <a href="mailto:gu.cgsoares@gmail.com.br">gu.cgsoares@gmail.com.br</a><br />
</address>

src/Presentation.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Fala galera!</h1>
<p>Bem vindos ao teste de implementação do Basket Microservice:</p>
<ul>
    <li><a href='http://localhost:53719/docs/' target="_blank">Clique aqui</a> para ver a documentação das APIs</li>
    <li>Inicie os testes das APIs criadas no menu 'Sandbox'</li>
</ul>

src/Presentation.Web/Views/Home/Sandbox.cshtml
@{
    ViewData["Title"] = "Sandbox";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Passo 1 - Criar um carrinho de compras</p>
<input type="button" value="Clique aqui para criar um carrinho" onclick="location.href='@Url.Action("Create", "Basket" )'" />

src/Presentation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Easy Commerce</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Easy Commerce</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Sandbox">Sandbox</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contatos</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Easy Commerce</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>